name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: openstudio-cmake-tools
  centos_version: centos9

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Registry image from lower case owner name
      run: |
        echo "REGISTRY_IMAGE=${GITHUB_REPOSITORY_OWNER,,}/${{ env.IMAGE_NAME }}" >>${GITHUB_ENV}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
        tags: |
          type=semver,pattern=v{{version}},prefix=${{ env.centos_version }}-
          type=semver,pattern=v{{major}}.{{minor}},prefix=${{ env.centos_version }}-
          type=semver,pattern=v{{major}},prefix=${{ env.centos_version }}-
          type=raw,value=main,enable=${{ github.ref_name == 'main' }},prefix=${{ env.centos_version }}-
          type=raw,value=latest,enable=${{ contains(github.ref, 'refs/tags') }},prefix=${{ env.centos_version }}-
          type=ref,event=pr,prefix=${{ env.centos_version }}-pr-

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: type=gha,scope=${{ github.repository }}
        cache-to: type=gha,scope=${{ github.repository }}
